export default Object.freeze({
  SplashScreen: 'SplashScreen',
  AppScreen: 'AppNavigator',
  WishLists: 'WishList',
  Orders: 'Orders',
  profile: 'Me',
  Address: 'Address',
  Currency: 'Currency',
  ContactUs: 'ContactUs',
  AboutScreen: 'AboutScreen',
  OrdersList: 'OrdersList',
  OrderDetails: 'MoreOrderItemDetails',
  LogIn: 'SignIn',
  LogOut: 'SignUp',
  Settings: 'Settings',
  ProductDetails: 'ProductDetails',
  Category: 'Category',
  Products: 'Products',
  Cart: 'Cart',
  SearchScreen: 'SearchScreen',
  AuthScreens: 'AuthScreens',
  NewAddress: 'NewAddress',
  Payment: 'Payment',
  PlaceOrder: 'OrderDetails',
  WelcomeScreen: 'WelcomeScreen',
});
